name: Add the latest wordle solutions for ES edition (normal, accent and science edition)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  addSolution:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm start
    - uses: stefanzweifel/git-auto-commit-action@v4
