name: Add the latest wordle solution for ES edition

on:
  workflow_dispatch:
  schedule:
    - cron: 58 * * * *

jobs:
  addSolution:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm start
    - run: |
        git config user.name javigaralva
        git config user.email javigaralva@gmail.com
        git add .
        git commit -m "Add Worldle solution for today"
        git push
